arb-dir: lib/l10n/arb
synthetic-package: false
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
preferred-supported-locales: [en, es, fr]
use-escaping: true
